/* WOA Early Birds — Phaser reference implementation */
(()=>{const host=document.getElementById("early-birds-canvas");if(!host||!window.Phaser)return;const $=s=>document.querySelector(s),scoreEl=$("#score"),timeEl=$("#time"),comboEl=$("#combo"),bestEl=$("#best"),statusEl=$("#status"),overlay=$("#game-overlay"),start=$("#start-game");let best=Number(localStorage.getItem("woaEarlyBirdsBest")||0);if(bestEl)bestEl.textContent="BEST "+best;
class EarlyBirds extends Phaser.Scene{
constructor(){super("EarlyBirds");this.running=false;this.score=0;this.combo=1;this.startedAt=0;this.birds=[];this.nextSpawn=0;this.difficulty=0;this.best=best}
preload(){this.load.image("yard","./assets/Highscrapparal.png?v=1");this.load.image("eric","./assets/eric.png?v=5");this.load.image("rufus","./assets/rufus-watch.svg?v=1");this.load.image("rufusAttack","./assets/rufus-attack.svg?v=1")}
create(){this.add.image(480,270,"yard").setDisplaySize(960,540);this.eric=this.add.image(315,390,"eric").setScale(.34);this.rufus=this.add.image(760,430,"rufus").setScale(.34);this.rufusAttack=this.add.image(760,430,"rufusAttack").setScale(.34).setVisible(false);this.input.on("pointerdown",p=>this.catchAt(p.x,p.y));setStatus("RUFUS IS WATCHING")}
startRound(){this.clearBirds();this.running=true;this.score=0;this.combo=1;this.difficulty=0;this.startedAt=performance.now();this.nextSpawn=0;scoreEl.textContent="0";comboEl.textContent="COMBO ×1";timeEl.textContent="00:00";overlay.style.display="none";setStatus("RUFUS IS WATCHING");this.rufus.setVisible(true);this.rufusAttack.setVisible(false)}
update(time,delta){if(!this.running)return;const elapsed=(performance.now()-this.startedAt)/1000;this.difficulty=Math.min(1,elapsed/90);timeEl.textContent=fmt(performance.now()-this.startedAt);if(time>=this.nextSpawn){this.spawnBird();this.nextSpawn=time+Math.max(1050,1900-this.difficulty*650)}for(const b of this.birds.slice()){if(!b.active)continue;b.y+=b.speed*delta/1000;b.rotation=Math.sin((time+b.seed)/350)*.06;if(b.y>555)this.missBird(b)}}
spawnBird(){const eagle=Math.random()<(.08+this.difficulty*.10),g=this.add.graphics(),x=90+Math.random()*780;g.x=x;g.y=-50;g.speed=105+this.difficulty*45+Math.random()*12;g.seed=Math.random()*9999;g.value=eagle?5:1;g.eagle=eagle;g.setInteractive(new Phaser.Geom.Circle(0,0,42),Phaser.Geom.Circle.Contains);g.on("pointerdown",()=>this.catchBird(g));this.drawBird(g,eagle);this.birds.push(g)}
drawBird(g,eagle){g.clear();g.fillStyle(eagle?0x232820:0x46545c,1);g.beginPath();g.moveTo(-45,8);g.quadraticCurveTo(-22,-27,4,-8);g.quadraticCurveTo(18,-38,48,-26);g.quadraticCurveTo(25,-4,10,2);g.quadraticCurveTo(33,12,47,31);g.quadraticCurveTo(18,27,0,14);g.quadraticCurveTo(-22,33,-44,30);g.quadraticCurveTo(-26,17,-18,7);g.quadraticCurveTo(-31,14,-45,8);g.closePath();g.fillPath();g.fillStyle(0x171510,1);g.fillTriangle(43,-25,66,-29,49,-10);g.fillStyle(0xf6edcf,1);g.fillCircle(31,-17,4);g.fillStyle(0x171510,1);g.fillCircle(32,-17,1.7);if(eagle){g.lineStyle(4,0xffad22,1);g.strokeCircle(31,-17,6)}}
catchAt(x,y){if(!this.running)return;const hit=this.birds.find(b=>b.active&&Phaser.Math.Distance.Between(x,y,b.x,b.y)<52);if(hit)this.catchBird(hit)}
catchBird(b){if(!b.active||!this.running)return;this.score+=b.value*this.combo;this.combo=Math.min(6,this.combo+1);scoreEl.textContent=this.score;comboEl.textContent="COMBO ×"+this.combo;setStatus(b.eagle?"RUFUS HAS SPOTTED THE EAGLE":"RUFUS IS GOING FOR IT");this.rufus.setVisible(false);this.rufusAttack.setVisible(true);this.tweens.add({targets:this.rufusAttack,x:b.x,y:b.y,duration:320,ease:"Cubic.easeOut",onComplete:()=>{if(!b.active)return;this.tweens.add({targets:b,scale:.05,alpha:0,duration:130,onComplete:()=>b.destroy()});setStatus("CHOMP. NICE ONE, RUFUS.");this.time.delayedCall(180,()=>{if(this.running){this.rufusAttack.x=760;this.rufusAttack.y=430;this.rufusAttack.setVisible(false);this.rufus.setVisible(true)}})}})}
missBird(b){if(!b.active)return;b.destroy();this.combo=1;comboEl.textContent="COMBO ×1";setStatus("TOO CLOSE...");this.tweens.add({targets:this.eric,angle:{from:-4,to:4},duration:70,yoyo:true,repeat:3});this.endRound()}
endRound(){if(!this.running)return;this.running=false;this.clearBirds();const elapsed=performance.now()-this.startedAt;timeEl.textContent=fmt(elapsed);const newBest=this.score>this.best;if(newBest){this.best=this.score;best=this.score;localStorage.setItem("woaEarlyBirdsBest",best);bestEl.textContent="BEST "+best}overlay.style.display="grid";overlay.querySelector("h3").textContent="ERIC SURVIVED";overlay.querySelector("p").innerHTML="Score: <b>"+this.score+"</b><br>"+(newBest?"New best.":"Rufus remains convinced this was a team effort.");start.textContent="PLAY AGAIN →";setStatus("SAFE... FOR NOW");this.rufus.setVisible(true);this.rufusAttack.setVisible(false);this.rufus.x=760;this.rufus.y=430}
clearBirds(){this.birds.forEach(b=>b.destroy());this.birds=[]}}
function fmt(ms){let s=Math.floor(ms/1000),m=Math.floor(s/60);s%=60;return String(m).padStart(2,"0")+":"+String(s).padStart(2,"0")}
function setStatus(t){if(statusEl)statusEl.textContent=t}
function boot(){if(window.WOA?.earlyBirds)return;const game=WOA.Game.boot({parent:"early-birds-canvas",width:960,height:540,background:"#11160e",scene:EarlyBirds});window.WOA.earlyBirds=game;start?.addEventListener("click",()=>game.scene.getScene("EarlyBirds").startRound())}
window.addEventListener("hashchange",()=>{if(location.hash==="#game")boot()});if(location.hash==="#game")boot();})();
